### ISSUE TITLE
장애물 설계

### ISSUE THREAD

**Issue by rhwodjs0518** [2024FALL-SWPP/team-project-for-2024-fall-swpp-team-18#31]

**Comment by jinsik03** [comment]
1. 나무 쓰러지기
2. 자동차 (플레이어와 가까워지면 감속할 수도)
3. 사람 (아이템과 헷갈릴수도?)
4. 뒤에서 눈덩이 날라옴

**Comment by jinsik03** [comment]
기본 도로: 5칸

1. 일반 나무가 3칸을 먹고 쓰러짐 -> 첫번째 나무 한쪽에서 쓰러지고 두번째 나무 반대편에서 쓰러짐. tree chunk.
2. 자동차가 도로를 가고 있음. 다만 플레이어의 속도가 더 빠르므로 자동차가 장애물이 됨.
- 이때 일부 자동차는 플레이어가 충분히 가까이 다가왔을 때 급정지해서 더욱 예측불가능한 상황을 만들 수 있음.
- 자동차가 5대 연속으로 나오고 무작위로 급정지하는 car chunk.
3. 사람들이 중간에 끼어들 수 있음.
- 연속적으로 3명 정도. people chunk
4. 눈덩이가 일정 시간? 마다 뒤에서 내려와서 보고 피해야됨
- snow chunk
5. 1번과 같이 나무가 연속적으로 쓰러짐. But 쓰러진 나무 사이에 간격이 너무 좁아 물리적으로 피할 수 없게 설정 -> 점프대를 놓아서 점프대를 밟아야만 무사히 건너갈 수 있도록 함. 
- jump chunk
