### ISSUE TITLE
아이템 설계

### ISSUE THREAD

**Issue by rhwodjs0518** [2024FALL-SWPP/team-project-for-2024-fall-swpp-team-18#32]

**Comment by jinsik03** [comment]
1. 속도 증가 - 기계공학부, 심볼: 톱니바퀴 or 스패너
2. 시간 지연(속도 감소) - 물리학부, 심볼: 모래시계 or 로렌츠 인자 공식
3. 생명 회복 - 의학부, 심볼: 하트 or 적십자가
4. 파이어볼 충전 - 화학부 (나무 불태워 없앰), 심볼: 실험 플라스크 or 불꽃
5. 코인 2배(만약 코인이 있다면) - 경제학부, 심볼: 달러 사인 or 코인 or 주식 그래프
6. 무적 or 자율주행 - 교수님, 심볼: 교수님 사진?
7. 실드(물리적 방벽 느낌) - 건축학부, 심볼: 건축 도면
8. 아이템 효과 2배(지속시간이나 속도, 회복량 등등) - 전기공학부, 심볼: 번개
9. 눈사태 느려짐 - 지구환경과학부, 심볼: 눈송이
10. 방향 조작키 바뀜 - 컴퓨터공학부, 심볼: 컴퓨터 or 키보드
11. 시야 제한(마리오카트 오징어 먹물 느낌) - 미대생, 심볼: 붓
12. 아이템 효과 봉쇄- 법대생(규제의 느낌), 심볼: 저울

모델링은 공통적인 사람 모델 + 손바닥 위에 해당 학부를 의미하는 심볼을 추가하는 걸로 생각.

+이 게임의 목적이 단순히 목표 지점 도착이 아닌, 점수를 도입한다고 하면 많은 학생들을 먹을수록(구출해서 같이 데려갈수록) 점수가 올라가도록 하면 좋겠음.(버프/디버프 상관없이. 그러면 디버프 학생들도 일부로 먹어서 좀 더 어려워질 수도?)

**Comment by jinsik03** [comment]
1. 학점 - A+(100), B+(50), B-(-30), C+(-10), F(-100) 5단계. (주된 점수 역할)
2. 속도 증가 - 기계공학부, 심볼: 톱니바퀴 or 스패너
3. 시간 지연(속도 감소) - 물리학부, 심볼: 모래시계 or 로렌츠 인자 공식
4. 생명 회복 - 의학부, 심볼: 하트 or 적십자가
5. 파이어볼 충전 - 화학부 (나무 불태워 없앰), 심볼: 실험 플라스크 or 불꽃
6. 학점 2배 - 교수님(교수님 사진), (-도 2배)
7. 방향 조작키 바뀜 - 컴퓨터공학부, 심볼: 컴퓨터 or 키보드
8. 시야 제한(마리오카트 오징어 먹물 느낌) - 미대생, 심볼: 붓

아이템 등장 형태: 5칸 중 3칸 정도로 동시에 등장, 마리오 카트 느낌 & 디버프 아이템은 따로 등장 가능
